info:
  contact: {}
paths:
  /api/v1/health:
    get:
      consumes:
      - application/json
      description: Check the health status of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health check
      tags:
      - health
  /dashboard/{formId}/analytics:
    get:
      consumes:
      - application/json
      description: Retrieve analytics for a form
      parameters:
      - description: Form ID
        in: path
        name: formId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get form analytics
      tags:
      - dashboard
  /dashboard/{formId}/passwords:
    get:
      consumes:
      - application/json
      description: Retrieve passwords for a form
      parameters:
      - description: Form ID
        in: path
        name: formId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get form passwords
      tags:
      - dashboard
    post:
      consumes:
      - application/json
      description: Create passwords for a form
      parameters:
      - description: Form ID
        in: path
        name: formId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Create form passwords
      tags:
      - dashboard
  /dashboard/{formId}/passwords/{passwordId}:
    delete:
      consumes:
      - application/json
      description: Delete passwords for a form
      parameters:
      - description: Form ID
        in: path
        name: formId
        required: true
        type: string
      - description: Password ID
        in: path
        name: passwordId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Delete form passwords
      tags:
      - dashboard
    patch:
      consumes:
      - application/json
      description: Update passwords for a form
      parameters:
      - description: Form ID
        in: path
        name: formId
        required: true
        type: string
      - description: Password ID
        in: path
        name: passwordId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Update form passwords
      tags:
      - dashboard
  /dashboard/{formId}/questions:
    get:
      consumes:
      - application/json
      description: Retrieve questions for a form
      parameters:
      - description: Form ID
        in: path
        name: formId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get form questions
      tags:
      - dashboard
  /dashboard/{formId}/responses:
    get:
      consumes:
      - application/json
      description: Retrieve responses for a form
      parameters:
      - description: Form ID
        in: path
        name: formId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get form responses
      tags:
      - dashboard
  /dashboard/{formId}/security:
    patch:
      consumes:
      - application/json
      description: Update security settings for a form
      parameters:
      - description: Form ID
        in: path
        name: formId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Update form security
      tags:
      - dashboard
  /dashboard/{formId}/settings:
    patch:
      consumes:
      - application/json
      description: Update settings for a form
      parameters:
      - description: Form ID
        in: path
        name: formId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Update form settings
      tags:
      - dashboard
  /edges:
    get:
      consumes:
      - application/json
      description: Retrieve a list of edges
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get all edges
      tags:
      - edges
    post:
      consumes:
      - application/json
      description: Create a new edge
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Create a new edge
      tags:
      - edges
  /edges/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an edge by ID
      parameters:
      - description: Edge ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Delete an edge
      tags:
      - edges
    patch:
      consumes:
      - application/json
      description: Update an existing edge by ID
      parameters:
      - description: Edge ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Update an edge
      tags:
      - edges
  /forms:
    get:
      consumes:
      - application/json
      description: Retrieve a list of forms
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get all forms
      tags:
      - forms
    post:
      consumes:
      - application/json
      description: Create a new form
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Create a new form
      tags:
      - forms
  /forms/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve a form by its ID
      parameters:
      - description: Form ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get a form by ID
      tags:
      - forms
  /forms/{id}/status:
    delete:
      consumes:
      - application/json
      description: Update the status of a form by ID
      parameters:
      - description: Form ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Update form status
      tags:
      - forms
    patch:
      consumes:
      - application/json
      description: Update the status of a form by ID
      parameters:
      - description: Form ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Update form status
      tags:
      - forms
  /projects:
    get:
      consumes:
      - application/json
      description: Retrieve a list of projects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get all projects
      tags:
      - projects
    post:
      consumes:
      - application/json
      description: Create a new project
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Create a new project
      tags:
      - projects
  /projects/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a project by ID
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Delete a project
      tags:
      - projects
    patch:
      consumes:
      - application/json
      description: Update an existing project by ID
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Update a project
      tags:
      - projects
  /questions:
    get:
      consumes:
      - application/json
      description: Retrieve a list of questions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get all questions
      tags:
      - questions
    post:
      consumes:
      - application/json
      description: Create a new question
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Create a new question
      tags:
      - questions
  /questions/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a question by ID
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Delete a question
      tags:
      - questions
    patch:
      consumes:
      - application/json
      description: Update an existing question by ID
      parameters:
      - description: Question ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Update a question
      tags:
      - questions
  /teams:
    get:
      consumes:
      - application/json
      description: Retrieve a list of teams
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get all teams
      tags:
      - teams
    post:
      consumes:
      - application/json
      description: Create a new team
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Create a new team
      tags:
      - teams
  /teams/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a team by ID
      parameters:
      - description: Team ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Delete a team
      tags:
      - teams
    patch:
      consumes:
      - application/json
      description: Update an existing team by ID
      parameters:
      - description: Team ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Update a team
      tags:
      - teams
swagger: "2.0"
